package scrum;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Luiza
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        dpnDesk = new javax.swing.JDesktopPane();
        btnStartQuiz = new javax.swing.JButton();
        lblSprintPlanningTxt = new javax.swing.JLabel();
        lblLamp = new javax.swing.JLabel();
        lblProductBacklog = new javax.swing.JLabel();
        lblSprintPlanning = new javax.swing.JLabel();
        lblSprint = new javax.swing.JLabel();
        lblProductOwner = new javax.swing.JLabel();
        lblScrumMaster = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblBacklogSprint = new javax.swing.JLabel();
        lblProductOwner2 = new javax.swing.JLabel();
        lblArrow1 = new javax.swing.JLabel();
        lblDevelopers = new javax.swing.JLabel();
        lblArrow2 = new javax.swing.JLabel();
        lblProductVision = new javax.swing.JLabel();
        lblProductBacklogTxt = new javax.swing.JLabel();
        lblBacklogSprintTxt = new javax.swing.JLabel();
        lblArrow3 = new javax.swing.JLabel();
        lblSprintTxt = new javax.swing.JLabel();
        lblRetrospectiveSprintTxt = new javax.swing.JLabel();
        lblReviewSprint = new javax.swing.JLabel();
        lblRetrospectiveSprint = new javax.swing.JLabel();
        lblDaily = new javax.swing.JLabel();
        lblProductTxt = new javax.swing.JLabel();
        lblReviewSprintTxt = new javax.swing.JLabel();
        lblProductOwner4 = new javax.swing.JLabel();
        lblDevelopers3 = new javax.swing.JLabel();
        lblScrumMaster3 = new javax.swing.JLabel();
        lblDevelopers2 = new javax.swing.JLabel();
        lblDevelopers5 = new javax.swing.JLabel();
        lblProductOwner3 = new javax.swing.JLabel();
        lblProductOwner5 = new javax.swing.JLabel();
        lblScrumMaster2 = new javax.swing.JLabel();
        lblScrumMaster4 = new javax.swing.JLabel();
        lblDevelopers4 = new javax.swing.JLabel();
        lblProductOwner6 = new javax.swing.JLabel();
        lblScrumMaster5 = new javax.swing.JLabel();
        lblDevelopers6 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchive = new javax.swing.JMenu();
        mnuArchiveRegistrationQuiz = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn Scrum");
        setResizable(false);

        dpnDesk.setBackground(new java.awt.Color(102, 102, 102));
        dpnDesk.setToolTipText("");

        btnStartQuiz.setBackground(new java.awt.Color(102, 102, 102));
        btnStartQuiz.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnStartQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-start.png"))); // NOI18N
        btnStartQuiz.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStartQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartQuizActionPerformed(evt);
            }
        });

        lblSprintPlanningTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSprintPlanningTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblSprintPlanningTxt.setText("Planejamento da Sprint");

        lblLamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-lamp_64px.png"))); // NOI18N

        lblProductBacklog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-backlog _128px.png"))); // NOI18N
        lblProductBacklog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProductBacklog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductBacklogMouseClicked(evt);
            }
        });

        lblSprintPlanning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-sprint-planning_128px.png"))); // NOI18N

        lblSprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-sprint.png"))); // NOI18N
        lblSprint.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblProductOwner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_128px.png"))); // NOI18N
        lblProductOwner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProductOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductOwnerMouseClicked(evt);
            }
        });

        lblScrumMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-scrum-master-64px.png"))); // NOI18N

        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product.png"))); // NOI18N

        lblBacklogSprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-backlog-sprint.png"))); // NOI18N

        lblProductOwner2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_64px.png"))); // NOI18N

        lblArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-arrow.png"))); // NOI18N

        lblDevelopers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_64px.png"))); // NOI18N

        lblArrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-arrow.png"))); // NOI18N

        lblProductVision.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblProductVision.setForeground(new java.awt.Color(255, 255, 255));
        lblProductVision.setText("Visão do Produto");

        lblProductBacklogTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblProductBacklogTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblProductBacklogTxt.setText("Backlog do Produto");

        lblBacklogSprintTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblBacklogSprintTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblBacklogSprintTxt.setText("Backlog da Sprint");

        lblArrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-arrow.png"))); // NOI18N

        lblSprintTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSprintTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblSprintTxt.setText("Sprint");

        lblRetrospectiveSprintTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRetrospectiveSprintTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblRetrospectiveSprintTxt.setText("Retrospectiva Sprint");

        lblReviewSprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-review-sprint.png"))); // NOI18N

        lblRetrospectiveSprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-retrospective_64px.png"))); // NOI18N

        lblDaily.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblDaily.setForeground(new java.awt.Color(255, 255, 255));
        lblDaily.setText("Reunião diária");

        lblProductTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblProductTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblProductTxt.setText("Incremento");

        lblReviewSprintTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblReviewSprintTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblReviewSprintTxt.setText("Revisão Sprint");

        lblProductOwner4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_64px.png"))); // NOI18N

        lblDevelopers3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_32px.png"))); // NOI18N

        lblScrumMaster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-scrum-master-64px.png"))); // NOI18N

        lblDevelopers2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_64px.png"))); // NOI18N

        lblDevelopers5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_64px.png"))); // NOI18N

        lblProductOwner3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_64px.png"))); // NOI18N

        lblProductOwner5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_32px.png"))); // NOI18N

        lblScrumMaster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-scrum-master-32px.png"))); // NOI18N

        lblScrumMaster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-scrum-master-64px.png"))); // NOI18N

        lblDevelopers4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_64px.png"))); // NOI18N

        lblProductOwner6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-product_owner_64px.png"))); // NOI18N

        lblScrumMaster5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-scrum-master-64px.png"))); // NOI18N

        lblDevelopers6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-developers_64px.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Scrum Master");

        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Product Owner");

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Developers");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-youtube.png"))); // NOI18N

        dpnDesk.setLayer(btnStartQuiz, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblSprintPlanningTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblLamp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductBacklog, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblSprintPlanning, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblSprint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblScrumMaster, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProduct, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblBacklogSprint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblArrow1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblArrow2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductVision, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductBacklogTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblBacklogSprintTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblArrow3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblSprintTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblRetrospectiveSprintTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblReviewSprint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblRetrospectiveSprint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDaily, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblReviewSprintTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblScrumMaster3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblScrumMaster2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblScrumMaster4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblProductOwner6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblScrumMaster5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(lblDevelopers6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnDesk.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpnDeskLayout = new javax.swing.GroupLayout(dpnDesk);
        dpnDesk.setLayout(dpnDeskLayout);
        dpnDeskLayout.setHorizontalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnDeskLayout.createSequentialGroup()
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblProductVision, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                .addComponent(lblProductOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(lblArrow1))))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(lblLamp)))
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lblProductBacklog, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblArrow2))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(lblProductOwner2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblProductBacklogTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)))
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblScrumMaster)
                                .addGap(18, 18, 18)
                                .addComponent(lblDevelopers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSprintPlanningTxt)
                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                .addComponent(lblSprintPlanning)
                                                .addGap(18, 18, 18)
                                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblProductOwner4)
                                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                                        .addComponent(lblArrow3)
                                                        .addGap(37, 37, 37)
                                                        .addComponent(lblBacklogSprint)))))
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                                        .addComponent(lblBacklogSprintTxt)
                                        .addGap(37, 37, 37))))))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnStartQuiz)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblProductOwner6))
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRetrospectiveSprintTxt)
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dpnDeskLayout.createSequentialGroup()
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblProductTxt))
                                    .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dpnDeskLayout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblScrumMaster4)
                                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblScrumMaster5)))
                                            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(dpnDeskLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblDevelopers6)
                                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(dpnDeskLayout.createSequentialGroup()
                                                    .addGap(30, 30, 30)
                                                    .addComponent(lblDevelopers5))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dpnDeskLayout.createSequentialGroup()
                                            .addGap(130, 130, 130)
                                            .addComponent(lblRetrospectiveSprint)
                                            .addGap(41, 41, 41)
                                            .addComponent(lblProduct))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblScrumMaster3)
                                .addGap(45, 45, 45)
                                .addComponent(lblDevelopers4))
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lblSprintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addComponent(lblSprint)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblProductOwner5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblScrumMaster2))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblDevelopers3))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblReviewSprint)))
                                .addGap(268, 268, 268))
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblReviewSprintTxt)
                                .addGap(20, 20, 20))))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblDevelopers2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                    .addContainerGap(925, Short.MAX_VALUE)
                    .addComponent(lblDaily)
                    .addGap(328, 328, 328)))
            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dpnDeskLayout.createSequentialGroup()
                    .addGap(430, 430, 430)
                    .addComponent(lblProductOwner3)
                    .addContainerGap(819, Short.MAX_VALUE)))
        );
        dpnDeskLayout.setVerticalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnDeskLayout.createSequentialGroup()
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblScrumMaster)
                                            .addComponent(lblDevelopers)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblDevelopers2)
                                        .addGap(25, 25, 25)))
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(lblArrow2))
                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(lblProductOwner4))
                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblProductBacklog, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                                        .addComponent(lblSprintPlanningTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblSprintPlanning))
                                                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(lblBacklogSprint)
                                                                    .addComponent(lblArrow3))))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblProductBacklogTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBacklogSprintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProductOwner2)
                                    .addComponent(lblLamp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addComponent(lblProductVision, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblProductOwner))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(lblArrow1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSprintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScrumMaster3)
                            .addComponent(lblDevelopers4)))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblDevelopers3)
                        .addGap(18, 18, 18)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductOwner5)
                            .addComponent(lblScrumMaster2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReviewSprintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetrospectiveSprint)
                            .addComponent(lblReviewSprint)
                            .addComponent(lblProduct))
                        .addGap(18, 18, 18)
                        .addComponent(lblRetrospectiveSprintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScrumMaster4)
                            .addComponent(lblDevelopers5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblScrumMaster5)
                            .addGroup(dpnDeskLayout.createSequentialGroup()
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblProductOwner6))
                                    .addGroup(dpnDeskLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDevelopers6)))))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                        .addComponent(btnStartQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dpnDeskLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(lblDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(534, Short.MAX_VALUE)))
            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dpnDeskLayout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(lblProductOwner3)
                    .addContainerGap(520, Short.MAX_VALUE)))
        );

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));

        menuArchive.setForeground(new java.awt.Color(255, 255, 255));
        menuArchive.setText("Arquivos");

        mnuArchiveRegistrationQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-register.png"))); // NOI18N
        mnuArchiveRegistrationQuiz.setText("Cadastro Quiz");
        mnuArchiveRegistrationQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchiveRegistrationQuizActionPerformed(evt);
            }
        });
        menuArchive.add(mnuArchiveRegistrationQuiz);

        menuBar.add(menuArchive);

        menuHelp.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp.setText("Ajuda");
        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpnDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartQuizActionPerformed
        // Carrega o quiz
        FrmQuiz frmQuiz = new FrmQuiz();
        dpnDesk.add(frmQuiz);
        frmQuiz.show();
    }//GEN-LAST:event_btnStartQuizActionPerformed

    private void mnuArchiveRegistrationQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchiveRegistrationQuizActionPerformed
        // Carrega o formulário de questões
        FrmQuestion frmQuestions = new FrmQuestion();
        dpnDesk.add(frmQuestions);
        frmQuestions.show();
    }//GEN-LAST:event_mnuArchiveRegistrationQuizActionPerformed

    private void lblProductBacklogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductBacklogMouseClicked
        PnlMessage pnlMessage = new PnlMessage();
        pnlMessage.setDescription("ddhishdisdksn");
        UIManager.put("OptionPane.minimumSize",new Dimension(300, 120));        
        JOptionPane.showMessageDialog(null, pnlMessage, "Customized Message Dialog", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_lblProductBacklogMouseClicked

    private void lblProductOwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductOwnerMouseClicked
        PnlMessage pnlMessage = new PnlMessage();
        pnlMessage.setDescription("deu certoooo");
        UIManager.put("OptionPane.minimumSize",new Dimension(300, 120));        
        JOptionPane.showMessageDialog(null, pnlMessage, "Customized Message Dialog", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_lblProductOwnerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MS Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMain frmMain = new FrmMain();
                frmMain.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frmMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartQuiz;
    private javax.swing.JDesktopPane dpnDesk;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel lblArrow1;
    private javax.swing.JLabel lblArrow2;
    private javax.swing.JLabel lblArrow3;
    private javax.swing.JLabel lblBacklogSprint;
    private javax.swing.JLabel lblBacklogSprintTxt;
    private javax.swing.JLabel lblDaily;
    private javax.swing.JLabel lblDevelopers;
    private javax.swing.JLabel lblDevelopers2;
    private javax.swing.JLabel lblDevelopers3;
    private javax.swing.JLabel lblDevelopers4;
    private javax.swing.JLabel lblDevelopers5;
    private javax.swing.JLabel lblDevelopers6;
    private javax.swing.JLabel lblLamp;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductBacklog;
    private javax.swing.JLabel lblProductBacklogTxt;
    private javax.swing.JLabel lblProductOwner;
    private javax.swing.JLabel lblProductOwner2;
    private javax.swing.JLabel lblProductOwner3;
    private javax.swing.JLabel lblProductOwner4;
    private javax.swing.JLabel lblProductOwner5;
    private javax.swing.JLabel lblProductOwner6;
    private javax.swing.JLabel lblProductTxt;
    private javax.swing.JLabel lblProductVision;
    private javax.swing.JLabel lblRetrospectiveSprint;
    private javax.swing.JLabel lblRetrospectiveSprintTxt;
    private javax.swing.JLabel lblReviewSprint;
    private javax.swing.JLabel lblReviewSprintTxt;
    private javax.swing.JLabel lblScrumMaster;
    private javax.swing.JLabel lblScrumMaster2;
    private javax.swing.JLabel lblScrumMaster3;
    private javax.swing.JLabel lblScrumMaster4;
    private javax.swing.JLabel lblScrumMaster5;
    private javax.swing.JLabel lblSprint;
    private javax.swing.JLabel lblSprintPlanning;
    private javax.swing.JLabel lblSprintPlanningTxt;
    private javax.swing.JLabel lblSprintTxt;
    private javax.swing.JMenu menuArchive;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem mnuArchiveRegistrationQuiz;
    // End of variables declaration//GEN-END:variables

}
